
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: git pull
    # - name: Run a multi-line script
    #   run: |
    #     pm2 restart all,
    #     echo test, and deploy your project.